MDCertificateAgreement accepted
MDomain                hvp.jplab.net
MDRenewMode            auto

<VirtualHost *:443>

  ServerName  hvp.jplab.net
  ServerAdmin dpsmith@bcm.edu
  SSLEngine   on

  DocumentRoot /var/www/hvp/html

  <Location /api>
    SetHandler       r-handler
    RFileHandler     /var/www/hvp/api/handler.r
    RSourceOnStartup /var/www/hvp/api/startup.r
  </Location>

</VirtualHost>


<VirtualHost *:80>
    ServerName hvp.jplab.net
    Redirect   302 / https://hvp.jplab.net/
</VirtualHost>
