# --- Globus Auth Configuration ---
provider        = "oidc"
oidc_issuer_url = "https://auth.globus.org"

# Minimize scope: keep "openid" (required) and "email"
scope            = "openid email"
oidc_email_claim = "email"
insecure_oidc_allow_unverified_email = true

# Memory-optimized cookie storage
session_store_type = "cookie"
cookie_secure      = true
cookie_domains     = "metadata.human-virome.org"
cookie_expire      = "12h"

# Run locally - Nginx will proxy to this
http_address = "127.0.0.1:4180"

# Dummy upstream since Nginx handles the actual application routing
upstreams = "file:///dev/null"

# Expose authentication headers (like Email and User) to Nginx
set_xauthrequest = true

# Whitelist individual emails here
# allowed_emails = [
#   "user1@arizona.edu",
#   "user2@nih.gov"
# ]

# Path to the file containing one email per line
#authenticated_emails_file = "/var/www/vbr/config/userlist.txt"

email_domains = [ "*" ]
# Restrict Globus auth to specific domains
# email_domains = [
#   "aiimsbhubaneswar.edu.in",
#   "arizona.edu",
#   "bcm.edu",
#   "biol.lu.se",
#   "broadinstitute.org",
#   "buffalo.edu",
#   "caltech.edu",
#   "chop.edu",
#   "colorado.edu",
#   ".cornell.edu",
#   "einsteinmed.edu",
#   ".harvard.edu",
#   "lbl.gov",
#   "med.umich.edu",
#   "mskcc.org",
#   "nativebio.org",
#   ".nih.gov",
#   "northshore.org",
#   "pnnl.gov",
#   "psu.edu",
#   "som.umaryland.edu",
#   "stanford.edu",
#   "twofrontiers.org",
#   "ucdavis.edu",
#   "uchc.edu",
#   ".ucla.edu",
#   ".ucsf.edu",
#   ".unc.edu",
#   ".upenn.edu",
#   "usc.edu",
#   ".utah.edu",
#   "uth.tmc.edu",
#   ".utoronto.ca",
#   "vanderbilt.edu",
#   "vumc.org",
#   "wisc.edu",
#   "wustl.edu",
#   "yale.edu"
# ]
