name: Update Production Website

on: 
  push: 
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Trigger `git pull` from Lightsail Instance
        run: curl -X POST -so /dev/null https://hvp.jplab.net/webhook/git-deploy || true
